/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsFileRouteImport } from './routes/docs/$file'
import { Route as ApiSubscriptionsCronRouteImport } from './routes/api/subscriptions/cron'
import { Route as ApiAuthChar91DotDotChar93RouteImport } from './routes/api/auth/[...]'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsFileRoute = DocsFileRouteImport.update({
  id: '/$file',
  path: '/$file',
  getParentRoute: () => DocsRoute,
} as any)
const ApiSubscriptionsCronRoute = ApiSubscriptionsCronRouteImport.update({
  id: '/api/subscriptions/cron',
  path: '/api/subscriptions/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthChar91DotDotChar93Route =
  ApiAuthChar91DotDotChar93RouteImport.update({
    id: '/api/auth/[./.]',
    path: '/api/auth/[./.]',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/mcp': typeof McpRoute
  '/transactions': typeof TransactionsRoute
  '/docs/$file': typeof DocsFileRoute
  '/api/subscriptions/cron': typeof ApiSubscriptionsCronRoute
  '/api/auth/[./.]': typeof ApiAuthChar91DotDotChar93Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/mcp': typeof McpRoute
  '/transactions': typeof TransactionsRoute
  '/docs/$file': typeof DocsFileRoute
  '/api/subscriptions/cron': typeof ApiSubscriptionsCronRoute
  '/api/auth/[./.]': typeof ApiAuthChar91DotDotChar93Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/mcp': typeof McpRoute
  '/transactions': typeof TransactionsRoute
  '/docs/$file': typeof DocsFileRoute
  '/api/subscriptions/cron': typeof ApiSubscriptionsCronRoute
  '/api/auth/[./.]': typeof ApiAuthChar91DotDotChar93Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/mcp'
    | '/transactions'
    | '/docs/$file'
    | '/api/subscriptions/cron'
    | '/api/auth/[./.]'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/mcp'
    | '/transactions'
    | '/docs/$file'
    | '/api/subscriptions/cron'
    | '/api/auth/[./.]'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/mcp'
    | '/transactions'
    | '/docs/$file'
    | '/api/subscriptions/cron'
    | '/api/auth/[./.]'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  McpRoute: typeof McpRoute
  TransactionsRoute: typeof TransactionsRoute
  ApiSubscriptionsCronRoute: typeof ApiSubscriptionsCronRoute
  ApiAuthChar91DotDotChar93Route: typeof ApiAuthChar91DotDotChar93Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$file': {
      id: '/docs/$file'
      path: '/$file'
      fullPath: '/docs/$file'
      preLoaderRoute: typeof DocsFileRouteImport
      parentRoute: typeof DocsRoute
    }
    '/api/subscriptions/cron': {
      id: '/api/subscriptions/cron'
      path: '/api/subscriptions/cron'
      fullPath: '/api/subscriptions/cron'
      preLoaderRoute: typeof ApiSubscriptionsCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/[./.]': {
      id: '/api/auth/[./.]'
      path: '/api/auth/[./.]'
      fullPath: '/api/auth/[./.]'
      preLoaderRoute: typeof ApiAuthChar91DotDotChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsFileRoute: typeof DocsFileRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsFileRoute: DocsFileRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  McpRoute: McpRoute,
  TransactionsRoute: TransactionsRoute,
  ApiSubscriptionsCronRoute: ApiSubscriptionsCronRoute,
  ApiAuthChar91DotDotChar93Route: ApiAuthChar91DotDotChar93Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
